### ISSUE TITLE
Questions de conception

### ISSUE THREAD

**Issue by mfld-fr** [kotec-le-raleur/regenerateur_pile_alcaline#1]
Bonjour @kotec-le-raleur ,

Merci pour avoir publié votre travail, qui m'intéresse à titre de référence, car je me suis lancé à mon tour dans l'expérimentation de la régénération de pile alcaline depuis quelques mois maintenant...

J'ai quelques questions sur votre montage :

1. Le courant pendant la charge est fixé par la tension d'alimentation (~5 V) et la résistance de charge (33 ohms), abstraction faite de la chute de tension émetteur-collecteur du PNP, soit de 100 à 115 mA pour une pile à tension sous charge de 1.2 à 1.7V. Comment avez-vous déterminé ce courant de charge ?

2. Le cycle comprend une charge suivie d'une décharge. Ce cycle charge / décharge est-il nécessaire pour l'efficacité de la régénération, et pourquoi un cycle charge / relaxation ne suffirait pas ? Comment avez-vous déterminé le rapport entre les durées de charge et de décharge ?

3. Vous indiquez  "ne pas avoir été convaincu" par les références de tensions internes 1V et 2.56V de l'ATTiny85. En quoi exactement ces références n'ont pas été utilisables et vous ont poussé à utiliser une référence externe de précision ?

**Comment by kotec-le-raleur** [comment]
Voiçi quelques réponses à vos interrogations.
1) j'ai pris un courant de charge qui ne provoquera pas de surchauffe ou de fuite d'électrolyte. Pour une pile AA, ( ma cible de départ) 100 mA  est une valeur raisonnable. J'ai dû lire cette valeur dans un article sur la régénération des alcalines , mais je ne sais plus où . Pour des piles plus grosses, on peut bien sùr augmenter le courant, mais mon montage est alimenté par l'USB du PC ou par petit chargeur, donc, on ne peut pas aller bien plus que 400mA

2) Le cycle en décharge me permet d'évaluer la résistance interne de la pile . Le rapport charge/décharge n'a pas vraiment d'importance, mais il faut privilégier la charge dans le timing .  Pas de calculs savants, juste un rapport de temps qui m'a semblé raisonnable.

3)Dans mon montage, le choix des références internes ne fonctionnait pas (ou mal). J'ai opté pour un TL431 pour deux raisons 
    a) j'aime bien ce circuit très pratique et multi usages. Il est fait pour ça et le fait bien
    b) j'en ai acheté une poche de 50 pour vraiment pas cher :-) et je veux les utiliser 
Voilà, mes impressions sur l'efficacité de ce "régénérateur" sont mitigés. La recharge dépend beaucoup de la pile, de son degrès de décharge, de sa marque . Les Ikéa étaient tès bien !
Pour remettre dans une télécommande ou une horloge, c'est OK.  Sinon c'est moyen , rien ne vaudra une pile neuve ou un accus NiZn (1.65V) ou à la rigueur un Ni-mh (1.2V)

Bye et bon bricolage avec ce montage.
RL

**Comment by mfld-fr** [comment]
Bonjour, merci d'avoir répondu... et d'accord avec votre conclusion. Je vois plus ça comme un cas d'école ou un entraînement au "DIY", et lors d'une présentation du montage à l'entourage, comme une occasion de sensibiliser sur le sujet de l'énorme gâchis dans l'usage actuel des piles, alors que les accumulateurs seraient bien plus indiqués dans nombre de cas courants.

1. Les recommandations sont effectivement de ne pas dépasser C/15, mais je pense qu'on pourrait aller plus loin dans la régulation avec une alimentation moins limitée que l'USB. J'ai par exemple trouvé sur internet une réalisation où la consigne en courant est calculée par l'utilisateur en fonction de la masse de la pile... Connaissant la relation entre la puissance thermique dissipée dans la pile (Pth = Rint * Ic ^ 2) et sa température, en rajoutant un capteur au contact de la pile et avec une consigne sur une température maximale, le MCU devrait pouvoir réguler un courant de charge optimal ?..
2. Connaissant la tension au repos après relaxation entre deux périodes de charge, il est possible de calculer une résistance interne pendant la charge. Par contre je ne sais pas si elle est égale à la résistance interne pendant la décharge ? Je ne suis donc pas certain que les périodes de décharges soient vraiment nécessaires, et s'il ne serait pas possible de simplifier le montage en même temps que diminuer le temps de la régénération ?
3. Je lis dans la documentation de l'ATTinyX5 (section 17.6.2) qu'il ne faut pas utiliser la première mesure de l'ADC juste après la mise en route des références internes de tension, ou après avoir commuté entre 2 références... or dans la configuration "usine", les références ne sont pas initialement actives (car pas de BO activé dans les fusibles), et je lis dans le code du core Arduino que la fonction `analogRead()` change le registre de sélection de la référence avant chaque mesure ?.. Avec un core "maison", je n'observe pas de problème de mesure de tension... D'où ma question pour déterminer si je ne suis pas passé à coté d'un défaut de ces références ?..

Après un temps d'étude des réalisations existantes (dont la vôtre), je suis parti sur une version améliorée en rendement, où j'ai remplacé la charge en tout ou rien par un convertisseur Buck piloté en PWM par le MCU, car je voudrais au final alimenter le régénérateur par un petit panneau solaire (tant qu'à régénérer des piles alcalines, faisons le avec de l’énergie verte :smile:)

![IMG_20230813_110910](https://github.com/kotec-le-raleur/regenerateur_pile_alcaline/assets/11684481/05e56416-c445-4084-a33a-09160c286d63)

**Comment by mfld-fr** [comment]
A part le flou qui persiste sur le problème rencontré avec les références internes de tension, les autres questions relèvent plus d'un autre développement -> je ferme le ticket.
